// Geometry invariant tests, driven by a real fixture: __fixtures__/geometry.json
// is the *actual* output of server/serialize.py's serialize_geometry() (which
// wraps engine/board.py's GEOMETRY singleton), generated by running the real
// Python engine -- not hand-constructed or guessed. See __fixtures__/README.md
// for how to regenerate it.
//
// hexToPixel's formula is standard, but "standard" isn't the same as
// "matches engine/board.py's actual DIRECTIONS/vertex/edge construction" --
// these tests check the geometric invariants a correct flat-top embedding
// must satisfy, against every one of the real board's 19 hexes, 54
// vertices, and 72 edges, rather than a couple of hand-picked examples.

import { describe, expect, test } from "vitest";
import type { Geometry } from "./api";
import fixtureGeometry from "./__fixtures__/geometry.json";
import { edgeEndpoints, hexCorners, hexToPixel, vertexPixels } from "./geometry";

const geometry = fixtureGeometry as Geometry;
const SIZE = 50;

function distance(
  a: { x: number; y: number },
  b: { x: number; y: number },
): number {
  return Math.hypot(a.x - b.x, a.y - b.y);
}

function angleDeg(p: { x: number; y: number }): number {
  return (Math.atan2(p.y, p.x) * 180) / Math.PI;
}

function normalizeAngle(deg: number): number {
  const mod = deg % 360;
  return mod < 0 ? mod + 360 : mod;
}

describe("hexToPixel", () => {
  test("the center hex maps to the origin", () => {
    expect(hexToPixel([0, 0, 0], SIZE)).toEqual({ x: 0, y: 0 });
  });

  test("all 6 canonical neighbor directions are equidistant from the center", () => {
    // engine/board.py's DIRECTIONS: the 6 unit steps in cube space. A valid
    // hex embedding must place every one of a hex's neighbors at the same
    // center-to-center distance.
    const directions: [number, number, number][] = [
      [1, -1, 0],
      [1, 0, -1],
      [0, 1, -1],
      [-1, 1, 0],
      [-1, 0, 1],
      [0, -1, 1],
    ];
    const distances = directions.map((d) => distance(hexToPixel(d, SIZE), { x: 0, y: 0 }));
    for (const d of distances) {
      expect(d).toBeCloseTo(distances[0], 6);
    }
    // For a regular hex grid, center-to-center distance between edge-adjacent
    // hexes is size * sqrt(3) (the hex's "width across flats").
    expect(distances[0]).toBeCloseTo(SIZE * Math.sqrt(3), 6);
  });

  test("consecutive canonical directions are 60 degrees apart", () => {
    const directions: [number, number, number][] = [
      [1, -1, 0],
      [1, 0, -1],
      [0, 1, -1],
      [-1, 1, 0],
      [-1, 0, 1],
      [0, -1, 1],
    ];
    const angles = directions.map((d) => normalizeAngle(angleDeg(hexToPixel(d, SIZE))));
    for (let i = 0; i < 6; i++) {
      const next = angles[(i + 1) % 6];
      let delta = next - angles[i];
      delta = ((delta % 360) + 360) % 360;
      expect(delta).toBeCloseTo(60, 6);
    }
  });
});

describe("vertexPixels + hexCorners, against the real board fixture", () => {
  const pixelsByVertexId = vertexPixels(geometry, SIZE);

  test("computes exactly one pixel per vertex id", () => {
    expect(pixelsByVertexId).toHaveLength(geometry.vertices.length);
    expect(pixelsByVertexId.every((p) => Number.isFinite(p.x) && Number.isFinite(p.y))).toBe(
      true,
    );
  });

  test("every hex's 6 corners sit at exactly `size` from its own center", () => {
    for (const hex of geometry.hexes) {
      const center = hexToPixel(hex.hex, SIZE);
      const corners = hexCorners(hex.vertex_ids, pixelsByVertexId);
      expect(corners).toHaveLength(6);
      for (const corner of corners) {
        expect(distance(center, corner)).toBeCloseTo(SIZE, 6);
      }
    }
  });

  test("a hex's 6 corners radiate around its center at 60-degree increments", () => {
    for (const hex of geometry.hexes) {
      const center = hexToPixel(hex.hex, SIZE);
      const corners = hexCorners(hex.vertex_ids, pixelsByVertexId);
      const angles = corners.map((c) =>
        normalizeAngle(angleDeg({ x: c.x - center.x, y: c.y - center.y })),
      );
      for (let i = 0; i < 6; i++) {
        let delta = angles[(i + 1) % 6] - angles[i];
        delta = ((delta % 360) + 360) % 360;
        // Corners are listed in engine/board.py's per-hex construction order,
        // which walks the hex consistently in one rotational direction, so
        // consecutive corners are 60 degrees apart the same way every time.
        expect(delta).toBeCloseTo(60, 6);
      }
    }
  });

  test("every edge's two vertices are exactly `size` apart (a hex's side length equals its circumradius)", () => {
    for (const edge of geometry.edges) {
      const [p1, p2] = edgeEndpoints(edge, pixelsByVertexId);
      expect(distance(p1, p2)).toBeCloseTo(SIZE, 6);
    }
  });

  test("every port edge is a real coastal edge with two distinct pixel endpoints", () => {
    const edgeById = new Map(geometry.edges.map((e) => [e.edge_id, e]));
    for (const portEdgeId of geometry.port_locations) {
      const edge = edgeById.get(portEdgeId);
      expect(edge).toBeDefined();
      const [p1, p2] = edgeEndpoints(edge!, pixelsByVertexId);
      expect(distance(p1, p2)).toBeCloseTo(SIZE, 6);
    }
  });
});
